version: "3.8"

services:
  backend:
    build: .
    container_name: fraud-backend
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./db:/app/db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: nginx:alpine
    container_name: fraud-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
